name = "nextjs-ssr-app"
compatibility_date = "2024-01-01"
node_compat = true

# Production environment (default)
[vars]
ENVIRONMENT = "production"

# Staging environment
[env.staging]
name = "nextjs-ssr-app-staging"
[env.staging.vars]
ENVIRONMENT = "staging"

# Worker size limit: 10 MiB (Paid) / 3 MiB (Free)
# Monitor compressed size during deployment