name = "nextjs-ssr-app"
compatibility_date = "2024-12-30"
compatibility_flags = [
  # Enable Node.js API
  # see https://developers.cloudflare.com/workers/configuration/compatibility-flags/#nodejs-compatibility-flag
  "nodejs_compat",
  # Allow to fetch URLs in your app
  # see https://developers.cloudflare.com/workers/configuration/compatibility-flags/#global-fetch-strictly-public
  "global_fetch_strictly_public"
]
main = ".open-next/worker.js"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
# The service should match the "name" of your worker
service = "nextjs-ssr-app"

# Uncomment and configure R2 bucket for Next.js caching
# [[r2_buckets]]
# binding = "NEXT_INC_CACHE_R2_BUCKET"
# bucket_name = "<BUCKET_NAME>"

# Uncomment and configure for custom domain
# [[routes]]
# pattern = "myapp.com/*"
# custom_domain = true

# Production environment (default)
[vars]
ENVIRONMENT = "production"

# Staging environment
[env.staging]
name = "nextjs-ssr-app-staging"

# Uncomment and configure for custom staging domain
# [[env.staging.routes]]
# pattern = "staging.myapp.com/*"
# custom_domain = true

[env.staging.vars]
ENVIRONMENT = "staging"

# Worker size limit: 10 MiB (Paid) / 3 MiB (Free)
# Monitor compressed size during deployment

# Custom Domain Configuration Examples:
# 
# For production with custom domain:
# [[routes]]
# pattern = "myapp.com/*"
# custom_domain = true
#
# For multiple domains:
# [[routes]]
# pattern = "myapp.com/*"
# custom_domain = true
# 
# [[routes]]
# pattern = "www.myapp.com/*"
# custom_domain = true
#
# For staging with custom domain:
# [[env.staging.routes]]
# pattern = "staging.myapp.com/*"
# custom_domain = true