name = "nextjs-ssr-app"
compatibility_date = "2024-01-01"
node_compat = true

# Uncomment and configure for custom domain
# [[routes]]
# pattern = "myapp.com/*"
# custom_domain = true

# Production environment (default)
[vars]
ENVIRONMENT = "production"

# Staging environment
[env.staging]
name = "nextjs-ssr-app-staging"

# Uncomment and configure for custom staging domain
# [[env.staging.routes]]
# pattern = "staging.myapp.com/*"
# custom_domain = true

[env.staging.vars]
ENVIRONMENT = "staging"

# Worker size limit: 10 MiB (Paid) / 3 MiB (Free)
# Monitor compressed size during deployment

# Custom Domain Configuration Examples:
# 
# For production with custom domain:
# [[routes]]
# pattern = "myapp.com/*"
# custom_domain = true
#
# For multiple domains:
# [[routes]]
# pattern = "myapp.com/*"
# custom_domain = true
# 
# [[routes]]
# pattern = "www.myapp.com/*"
# custom_domain = true
#
# For staging with custom domain:
# [[env.staging.routes]]
# pattern = "staging.myapp.com/*"
# custom_domain = true