name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main
      - production
  pull_request:
    branches:
      - main
      - production
  workflow_dispatch: # Allow manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test and Lint
    outputs:
      build-cache-key: ${{ steps.cache-keys.outputs.build-cache-key }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate cache keys
        id: cache-keys
        run: |
          echo "build-cache-key=build-${{ runner.os }}-${{ hashFiles('package-lock.json') }}-${{ hashFiles('**/*.ts', '**/*.tsx', '**/*.js', '**/*.jsx', 'next.config.js', 'tailwind.config.js', 'postcss.config.js', 'wrangler.toml') }}" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.12"
          cache: "npm"

      - name: Cache Next.js build
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
            .next/standalone
            .next/static
          key: ${{ steps.cache-keys.outputs.build-cache-key }}
          restore-keys: |
            build-${{ runner.os }}-${{ hashFiles('package-lock.json') }}-
            build-${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Build application
        run: npm run build

      - name: Cache build artifacts
        uses: actions/cache/save@v4
        if: always()
        with:
          path: |
            .next
            node_modules
          key: artifacts-${{ github.sha }}-${{ github.run_id }}

  deploy-staging:
    runs-on: ubuntu-latest
    name: Deploy to Staging
    needs: test
    if: github.event_name == 'pull_request'
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.12"
          cache: "npm"

      - name: Restore build artifacts
        id: restore-build-artifacts
        uses: actions/cache/restore@v4
        with:
          path: |
            .next
            node_modules
          key: artifacts-${{ github.sha }}-${{ github.run_id }}
          fail-on-cache-miss: false

      - name: Install dependencies (if cache miss)
        if: steps.restore-build-artifacts.outputs.cache-hit != 'true'
        run: npm ci

      - name: Cache Next.js build (restore)
        if: steps.restore-build-artifacts.outputs.cache-hit != 'true'
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
            .next/standalone
            .next/static
          key: ${{ needs.test.outputs.build-cache-key }}
          restore-keys: |
            build-${{ runner.os }}-${{ hashFiles('package-lock.json') }}-
            build-${{ runner.os }}-

      - name: Build application (if cache miss)
        if: steps.restore-build-artifacts.outputs.cache-hit != 'true'
        run: npm run build

      - name: Deploy to Cloudflare Workers (Staging)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --env staging
          workingDirectory: .
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Notify staging deployment success
        if: success()
        run: |
          echo "🚀 Deployment to staging successful!"
          if [ -n "${{ vars.CUSTOM_DOMAIN }}" ]; then
            echo "Staging URL: https://staging.${{ vars.CUSTOM_DOMAIN }}"
          elif [ -n "${{ vars.CLOUDFLARE_SUBDOMAIN }}" ]; then
            echo "Staging URL: https://nextjs-ssr-app-staging.${{ vars.CLOUDFLARE_SUBDOMAIN }}.workers.dev"
          else
            echo "Staging URL: https://nextjs-ssr-app-staging.your-subdomain.workers.dev"
          fi

      - name: Notify staging deployment failure
        if: failure()
        run: |
          echo "❌ Deployment to staging failed!"
          echo "Check the logs above for details."

  deploy-production:
    runs-on: ubuntu-latest
    name: Deploy to Production
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.12"
          cache: "npm"

      - name: Restore build artifacts
        id: restore-build-artifacts
        uses: actions/cache/restore@v4
        with:
          path: |
            .next
            node_modules
          key: artifacts-${{ github.sha }}-${{ github.run_id }}
          fail-on-cache-miss: false

      - name: Install dependencies (if cache miss)
        if: steps.restore-build-artifacts.outputs.cache-hit != 'true'
        run: npm ci

      - name: Cache Next.js build (restore)
        if: steps.restore-build-artifacts.outputs.cache-hit != 'true'
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
            .next/standalone
            .next/static
          key: ${{ needs.test.outputs.build-cache-key }}
          restore-keys: |
            build-${{ runner.os }}-${{ hashFiles('package-lock.json') }}-
            build-${{ runner.os }}-

      - name: Build application (if cache miss)
        if: steps.restore-build-artifacts.outputs.cache-hit != 'true'
        run: npm run build

      - name: Deploy to Cloudflare Workers (Production)
        run: npm run deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Notify deployment success
        if: success()
        run: |
          echo "🚀 Deployment to production successful!"
          if [ -n "${{ vars.CUSTOM_DOMAIN }}" ]; then
            echo "Application URL: https://${{ vars.CUSTOM_DOMAIN }}"
          elif [ -n "${{ vars.CLOUDFLARE_SUBDOMAIN }}" ]; then
            echo "Application URL: https://nextjs-ssr-app.${{ vars.CLOUDFLARE_SUBDOMAIN }}.workers.dev"
          else
            echo "Application URL: https://nextjs-ssr-app.your-subdomain.workers.dev"
          fi

      - name: Notify deployment failure
        if: failure()
        run: |
          echo "❌ Deployment to production failed!"
          echo "Check the logs above for details."
